//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dersler()
        {
            this.İliski = new HashSet<İliski>();
        }
    
        public int id { get; set; }
        public string DersAdı { get; set; }
        public Nullable<int> BölümİD { get; set; }
        public Nullable<int> AKTS { get; set; }
        public Nullable<int> Sınıf { get; set; }
    
        public virtual Bölümler Bölümler { get; set; }
        public virtual Sınıflar Sınıflar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<İliski> İliski { get; set; }
    }
}
