//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class İletisim
    {
        public int id { get; set; }
        public string İleti { get; set; }
        public Nullable<int> HocaİD { get; set; }
    
        public virtual Hocalar Hocalar { get; set; }
    }
}
