//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class İliski
    {
        public int id { get; set; }
        public Nullable<int> HocaİD { get; set; }
        public Nullable<int> DersİD { get; set; }
        public Nullable<int> ÖgrenciİD { get; set; }
        public Nullable<int> Vize { get; set; }
        public Nullable<int> Final { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Hocalar Hocalar { get; set; }
        public virtual Öğrenci Öğrenci { get; set; }
    }
}
