//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ÖğrenciBilgiSistemiEntities : DbContext
    {
        public ÖğrenciBilgiSistemiEntities()
            : base("name=ÖğrenciBilgiSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Bölümler> Bölümler { get; set; }
        public virtual DbSet<Dersler> Dersler { get; set; }
        public virtual DbSet<Duyuru> Duyuru { get; set; }
        public virtual DbSet<Hocalar> Hocalar { get; set; }
        public virtual DbSet<İletisim> İletisim { get; set; }
        public virtual DbSet<İliski> İliski { get; set; }
        public virtual DbSet<Öğrenci> Öğrenci { get; set; }
        public virtual DbSet<Sınıflar> Sınıflar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
