//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Öğrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Öğrenci()
        {
            this.İliski = new HashSet<İliski>();
        }
    
        public int id { get; set; }
        public string İsimSoyisim { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> Yas { get; set; }
        public Nullable<long> Telefon { get; set; }
        public Nullable<int> BölümİD { get; set; }
        public string Cinsiyet { get; set; }
    
        public virtual Bölümler Bölümler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<İliski> İliski { get; set; }
    }
}
